-- MySQL Script generated by MySQL Workbench
-- Tue Oct 24 09:41:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb_java
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb_java
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_java` DEFAULT CHARACTER SET utf8 ;
USE `mydb_java` ;

-- -----------------------------------------------------
-- Table `mydb_java`.`Hero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_java`.`Hero` (
  `id_hero` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) NULL,
  `name` VARCHAR(45) NULL,
  `hp` INT NULL,
  `attack` INT NULL,
  `offensive_item_id` INT NULL,
  `defensive_item_id` INT NULL,
  PRIMARY KEY (`id_hero`),
  UNIQUE INDEX `id_UNIQUE` (`id_hero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_java`.`Plateau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_java`.`Plateau` (
  `id_cases` INT NOT NULL AUTO_INCREMENT,
  `nom_event_case` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cases`),
  UNIQUE INDEX `id_cases_UNIQUE` (`id_cases` ASC) VISIBLE)
ENGINE = InnoDB;

CREATE USER 'root' ;

GRANT ALL ON `mydb_java`.* TO 'root';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
